//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 LSApp.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_LSAppTYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_CARDSETING              310
#define IDD_DIALOG1                     311
#define IDB_BITMAP_BUTTON1              312
#define IDD_DIALOG2                     313
#define IDD_DLG_DEVICESET               314
#define IDD_DLG_GEYIN                   315
#define IDD_DLG_JILISET                 316
#define IDD_DlgCom                      317
#define IDI_ICON1                       318
#define IDD_DlgBcakGround               318
#define IDD_DIALOGRME                   319
#define IDD_DlgBlueTest                 322
#define IDD_DlgBlueEre                  323
#define IDD_dlgFr                       324
#define IDD_dlgthd                      325
#define IDD_dlgthd_n                    326
#define IDD_dlgrub                      327
#define IDD_dlgPhase                    328
#define IDD_dlgSensitivity              329
#define IDD_jilisetnew                  330
#define IDD_StartPage                   332
#define IDD_devicemanange               333
#define IDD_MYCONTROL1                  335
#define IDR_MYCONTROL                   336
#define IDD_dlgcalibration              337
#define IDD_calibrationinput            338
#define IDD_calibrationoutput           339
#define IDD_DlgBorderLineSettings       341
#define IDD_limitsItem                  342
#define IDD_dlgAlgoriSettinds           343
#define IDD_dlgFrsettings               344
#define IDD_dlgTHDsettings              345
#define IDD_dlgPlayandRecord            346
#define IDD_dlgRBsettings               347
#define IDD_dlgCaculateSet              348
#define IDD_dlgCyclesTestSet            349
#define IDD_DlgInput                    350
#define IDD_DlgResShow                  351
#define IDD_DIALOG3                     355
#define IDD_DIgTestProcess              357
#define IDD_DlgTestResManage            358
#define IDD_DlgWaveShow                 359
#define IDD_DlgGetInput                 360
#define IDR_MENU1                       361
#define IDR_MENUJiliSet                 361
#define IDD_DlgScanLot                  362
#define IDD_DlgGradle                   363
#define IDB_BITMAP5                     374
#define IDR_BMP1                        378
#define IDB_BITMAP2                     380
#define IDB_BITMAP1                     381
#define IDB_BITMAP3                     382
#define IDD_DlgLogin                    383
#define IDD_DIALOG4                     384
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_BUTTON4                     1003
#define IDC_LIST1                       1004
#define IDC_BtnStopJiaozhun             1004
#define IDC_CMB_INPUT                   1005
#define IDC_CMB_INPUTINSIDE             1006
#define IDC_BUTTON5                     1006
#define IDC_CMB_YINXIANG                1007
#define IDC_JILISET                     1007
#define IDC_devicesaveout               1007
#define IDC_BUTTON9                     1007
#define IDC_CMB_YINXIANG2               1008
#define IDC_GENXIN                      1008
#define IDC_STATMS                      1009
#define IDC_STATV                       1010
#define IDC_EDITV                       1011
#define IDC_RES                         1012
#define IDC_BUTTON6                     1013
#define IDC_vvv                         1014
#define IDC_COMPINLV                    1015
#define IDC_COMBO2                      1016
#define IDC_COMSHENGYA                  1016
#define IDC_limitscmbtestitemmuti       1016
#define IDC_eretestOutcom               1016
#define IDC_EDITSHENGYA                 1017
#define IDC_limitscmbtestitemsingle     1017
#define IDC_EDITSHENGYA2                1018
#define IDC_EDITCHUSHIDIANYA            1018
#define IDC_CmbPort                     1018
#define IDC_DataBit                     1019
#define IDC_EDITCHUSHIDIANYA2           1019
#define IDC_StopBit                     1020
#define IDC_CmbCheck                    1021
#define IDC_CmbBound                    1022
#define IDC_BtnOpen                     1023
#define IDC_BtnClose                    1024
#define IDC_BtnSend                     1025
#define IDC_BtnRecive                   1026
#define IDC_EDITSEN1                    1027
#define IDC_EDITSEN2                    1028
#define IDC_recordtime                  1028
#define IDC_COMBO1                      1029
#define IDC_PICRME                      1030
#define IDC_COMBbeipin                  1030
#define IDC_EDIT1                       1031
#define IDC_COMBjilitype                1031
#define IDC_RADIO1                      1032
#define IDC_limitsdown                  1032
#define IDC_EDIT2                       1032
#define IDC_editalogriends              1032
#define IDC_jilieqPath                  1032
#define IDC_ZSDEVICENAME                1033
#define IDC_limitsdown2                 1033
#define IDC_EDIT3                       1033
#define IDC_ZSDEVICETYPE                1034
#define IDC_EDIT6                       1034
#define IDC_BUTTON7                     1035
#define IDC_EDITdianshu                 1035
#define IDC_BUTTON8                     1036
#define IDC_EDITtestpinlv               1036
#define IDC_SENDCOMMAND                 1037
#define IDC_BUTTON10                    1037
#define IDC_eretime                     1038
#define IDC_cmbtestItem                 1039
#define IDC_testResLable                1040
#define IDC_ZSRESKKK                    1041
#define IDC_CHECKPhase                  1042
#define IDC_CHECKSensitivity            1043
#define IDC_TAB1                        1044
#define IDC_EreID                       1045
#define IDC_CHECKFR                     1046
#define IDC_fmax                        1046
#define IDC_CHECKTHD                    1047
#define IDC_EDITpinlv                   1047
#define IDC_CHECKTHD_N                  1048
#define IDC_pictrue                     1048
#define IDC_CHECKRub_Buzz               1049
#define IDC_EDITXSCALE                  1049
#define IDC_EDITYSCALE                  1050
#define IDC_CHECKfenli                  1050
#define IDC_mycontrolchname             1058
#define IDC_mycontroldrivername         1059
#define IDC_mycontroldeviceName         1060
#define IDC_mycontrolchnames            1061
#define IDC_mycontrolfs                 1062
#define IDC_mycontroldevicename2        1063
#define IDC_devicemanagetotalpage       1064
#define IDC_mycontrolbits               1064
#define IDC_devicemanagecurpage         1065
#define IDC_mycontrolsenOrzengyi        1065
#define IDC_STATIC2                     1066
#define IDC_devicemanagetotalpage2      1067
#define IDC_devicemanagecurpage2        1068
#define IDC_stimdrawnew                 1068
#define IDC_editjilisetnewv             1069
#define IDC_editjilisetnewstart         1070
#define IDC_editjilisetnewstop          1071
#define IDC_COMBfs                      1072
#define IDC_jilinewcycle                1073
#define IDC_jilinewmintime              1074
#define IDC_siglastep                   1075
#define IDC_jilif1                      1076
#define IDC_TREE1                       1077
#define IDC_editcalibrationdevicename   1078
#define IDC_devicesavein                1079
#define IDC_editcalbraininputval        1079
#define IDC_editcalibrationoutvp        1079
#define IDC_EDIToutvv                   1080
#define IDC_editcalbrafs                1080
#define IDC_showdatachartname           1081
#define IDC_editcalibrationinputVrms    1081
#define IDC_editcalibrationoutAPva      1081
#define IDC_CHART                       1082
#define IDC_editcalibrationinputVPval   1082
#define IDC_showdataYtitle              1086
#define IDD_DlgDataShow                 1086
#define IDC_showdataX                   1087
#define IDC_jilinewTime                 1088
#define IDC_devicemangerecord           1089
#define IDC_devicemangeplay             1090
#define IDC_limitsitemTitle             1091
#define IDC_bordersettingpic            1094
#define IDC_limitsup                    1096
#define IDC_limitsup2                   1097
#define IDC_limitscmbunits              1098
#define IDC_limitsHz                    1099
#define IDC_checklimitssingleup         1100
#define IDC_checklimitsmutiup           1101
#define IDC_CHECK1                      1101
#define IDC_checklimitsmutidown         1102
#define IDC_CHECK2                      1102
#define IDC_checklimitssingledown       1103
#define IDC_CHECK3                      1103
#define IDC_CHECK4                      1104
#define IDC_CHECK5                      1105
#define IDC_CHECK6                      1106
#define IDC_CHECK7                      1107
#define IDC_CHECK8                      1108
#define IDC_CHECK9                      1109
#define IDC_CHECK10                     1110
#define IDC_CHECK11                     1111
#define IDC_CHECK12                     1112
#define IDC_CHECK13                     1113
#define IDC_CHECK14                     1114
#define IDC_CHECK15                     1115
#define IDC_CHECK16                     1116
#define IDC_CHECKendofhamnics           1117
#define IDC_RADIO2                      1118
#define IDC_RADIO3                      1119
#define IDC_alogrimsettree              1120
#define IDC_alogrithsetthdmincycles     1121
#define IDC_EDIT4                       1122
#define IDC_EDIT5                       1123
#define IDC_SPIN1                       1124
#define IDC_datashowTestResult          1125
#define IDC_EDIThamnicStart             1127
#define IDC_eretestIncom                1128
#define IDC_LIST2                       1129
#define IDC_calibrainputDevices         1130
#define IDC_calibraoutputdevices        1131
#define IDC_COMoutcmbdevice             1131
#define IDC_editalogriendsRB            1132
#define IDC_CHECKendofhamnicsRB         1133
#define IDC_EDIThamnicStartRB           1134
#define IDC_IECRB                       1135
#define IDC_IEEERB                      1136
#define IDC_eretestTestTimes            1137
#define IDC_EDITtestId                  1138
#define IDC_caculatesetDotNum           1139
#define IDC_EDITereTestCycles           1140
#define IDC_cmbCyclesTestSetItems       1141
#define IDC_editCyclesTestSetTimes      1142
#define IDC_editCyclesTestSetperid      1143
#define IDC_STATICgongfang              1144
#define IDC_STATICoutdevicemange        1145
#define IDC_STATICvp                    1146
#define IDC_STATICcalindel              1147
#define IDC_EDITinputvolaty             1148
#define IDC_EDIToutputvolaty            1149
#define IDC_STATICduodian               1150
#define IDC_EDITinputvolatyAP           1150
#define IDC_STATICbiaozhun              1151
#define IDC_EDIToutputvolatyAP          1151
#define IDC_STATICdiscardtime           1152
#define IDC_STATICaddcishu              1153
#define IDC_STATICrbaddcishu            1154
#define IDC_STATICrbbiozhun             1155
#define IDC_STATICtest                  1156
#define IDC_STATICerectl                1157
#define IDC_TREEanalysis                1158
#define IDC_STATIC8                     1160
#define IDC_STATIC9                     1161
#define IDC_STATIC10                    1162
#define IDC_STATIC13                    1163
#define IDC_STATIC14                    1164
#define IDC_STATIC16                    1165
#define IDC_STATIC17                    1166
#define IDC_STATIC19                    1167
#define IDC_InputDlgCaption             1169
#define IDC_InputDlgEdit                1170
#define IDC_InputDlgCaption2            1171
#define IDC_resshowitemname             1171
#define IDC_EDITresshow                 1172
#define IDC_uintresshow                 1173
#define IDC_resshowPolarity             1175
#define IDC_INKPICTURE1                 1177
#define IDC_processPic                  1178
#define IDC_ereTestResnew               1179
#define IDC_LIST1TestRes                1180
#define IDC_waveshowPic                 1181
#define IDC_jilisetCheckEQ              1182
#define IDC_getinputname                1183
#define IDC_EDITgetinput                1184
#define IDC_cmb_inputdialog             1185
#define IDC_SCROLLBAR1                  1186
#define IDC_STATIC_TIPS                 1187
#define IDC_IPaddress                   1188
#define IDC_editpasswd                  1189
#define IDC_cmbUseName                  1190
#define IDC_COMBO3                      1191
#define IDC_IPADDRESS1                  1192
#define IDC_BUTTON_OK                   1193
#define IDI_LK                          3119
#define ST                              32771
#define Authroty                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_MKPZ                         32775
#define ID_AUTHORITY                    32776
#define ID_MIMA                         32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_DOTSET                       32782
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_32785                        32785
#define ID_START_CYCLES                 32786
#define ID_STOP_CYCLES                  32787
#define ID_CYCLES_SET                   32788
#define ID_32789                        32789
#define ID_VIEW_RES                     32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_32797                        32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        385
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1194
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
